// This file is automatically generated from your CSS. Any edits will be overwritten.
export const container: string;
export const contentWrapper: string;
export const content: string;
export const nav: string;
export const navItem: string;
